FROM debian:sid-slim
RUN apt-get update && apt-get install --no-install-recommends -y \
  cmake \
  doxygen \
  graphviz \
  ninja-build \
  zlib1g-dev \
  libboost-dev \
  libgtest-dev \
  libcereal-dev \
  libbenchmark-dev \
  build-essential \
  git \
  ca-certificates
COPY . /src
WORKDIR /src

ENV LC_ALL=C.UTF-8
ENV CXXFLAGS="-g -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -O3 -std=c++17 -fconcepts"

#RUN mkdir /build_unit
#WORKDIR /build_unit
#RUN cmake -DCMAKE_BUILD_TYPE=None -GNinja -DCMAKE_VERBOSE_MAKEFILE=ON /src/test/unit
#RUN ninja -j$(nproc) -v

RUN mkdir /build_documentation
WORKDIR /build_documentation
RUN cmake -DCMAKE_BUILD_TYPE=None -GNinja -DCMAKE_VERBOSE_MAKEFILE=ON /src/test/documentation
RUN ninja -j$(nproc) -v
RUN MESON_TESTTHREADS=$(nproc) ninja test
